### ISSUE TITLE
Change address command ID for single relay

### ISSUE THREAD

**Issue by guybrush7** [sparkfun/SparkFun_Qwiic_Relay_Arduino_Library#3]
The `changeAddress` function sends command ID 0xC7 (`ADDRESS_LOCATION`). However, the SparkFun Qwiic Single Relay uses command ID 0x03 (`COMMAND_CHANGE_ADDRESS`).

Tested on Qwiic Single Relay. Could not change address with current version. Changing `ADDRESS_LOCATION` to 0x03 allowed it to work.

**Comment by binomnom** [comment]
thank you for this comment. this would have taken so long to troubleshoot.
that's quite a serious mistake

**Comment by ethanhjennings** [comment]
Thank you! I was pulling my hair trying to figure out why I couldn't change the address. Could we get a fix pulled in that works for both single and multiple relays?

**Comment by ethanhjennings** [comment]
I added another pull request that allows using either the change address command for single or quad relays so that it doesn't break existing users.

**Comment by edspark** [comment]
Thank you for the pull request @ethanhjennings and @binomnom ! I did not pull them in, because I formatted the source files before I even started looking at them. I know this is late, but nonetheless thank you very much. I added the changes suggested in your pull requests and everything seems to be hunky dory!
